<?php

// Require
require_once '/var/www/html/Radius/autoload.php';

// Suggest

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'dapphp\\radius\\eappacket' => '/EAPPacket.php',
                'dapphp\\radius\\mschapv2packet' => '/MsChapV2Packet.php',
                'dapphp\\radius\\radius' => '/Radius.php',
                'dapphp\\radius\\vendorid' => '/VendorId.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd

// Files
